### ISSUE TITLE
无法生成html报告

### ISSUE THREAD

**Issue by dem0ns** [opensec-cn/chip#3]
php chip.phar check xxx
这条语句是可以的，并且会显示很多报告

php chip.phar check xxx -r html -o report.html
这样执行之后就什么都没有显示，也没有报告

CentOS Linux release 7.7.1908 (Core)
非root用户下，目录也是和用户权限对应的，有写入权限

**Comment by Cyc1e183** [comment]
> 
> 
> php chip.phar check xxx
> 这条语句是可以的，并且会显示很多报告
> 
> php chip.phar check xxx -r html -o report.html
> 这样执行之后就什么都没有显示，也没有报告
> 
> CentOS Linux release 7.7.1908 (Core)
> 非root用户下，目录也是和用户权限对应的，有写入权限

同问题解决了，这个是因为批量的时候缓存不够中途崩了，php.ini里把memory_limit调大就好了

**Comment by phith0n** [comment]
感谢测试，之前没复现这个问题

**Comment by justmd5** [comment]
使用 php -d memory_limit=-1 chip.phar check xxx -r html -o report.html 临时修改下内存限制就好
